var linkUrls = [
	[
		"game_animal/game_4_2_1_easy.html", 
		"game_animal/game_4_2_1_normal.html", 
		"game_animal/game_4_2_1_hard.html"
	],
	[
		"game_jungle/game_4_2_2_easy.html", 
		"game_jungle/game_4_2_2_normal.html", 
		"game_jungle/game_4_2_2_hard.html"
	],
	[
		"game_world/game_4_2_3_easy.html", 
		"game_world/game_4_2_3_normal.html", 
		"game_world/game_4_2_3_hard.html"
	],
	[
		"game_animal/game_4_2_4_easy.html", 
		"game_animal/game_4_2_4_normal.html", 
		"game_animal/game_4_2_4_hard.html"
	],
	[
		"game_jungle/game_4_2_5_easy.html", 
		"game_jungle/game_4_2_5_normal.html", 
		"game_jungle/game_4_2_5_hard.html"
	],
	[
		"game_world/game_4_2_6_easy.html", 
		"game_world/game_4_2_6_normal.html", 
		"game_world/game_4_2_6_hard.html"
	],
]